### ISSUE TITLE
number of arguments in sample v

### ISSUE THREAD

**Issue by krijkamp** [DARTH-git/darthtools#3]
In our old samplev, we used with students in previous courses we had two arguments.
samplev(m.P, 1)  

If we ask student to "upgrade" to darthtools we have to make sure their code still works if they have a value. Can we make the function in a way that if this 1 is added it will ignore it?

**Comment by alanyang0924** [comment]
I changed it back to the previous version with 2 arguments, should be compatible with previous versions of our code now.

**Comment by alanyang0924** [comment]
I changed it back to the previous version with 2 arguments, should be compatible with previous versions of our code now.

**Comment by alanyang0924** [comment]
I changed it back to the previous version with 2 arguments, should be compatible with previous versions of our code now.
